# ===== playbooks/13-setup-alertmanager.yml =====
- name: Deploy Alertmanager
  hosts: 192.168.2.50
  become: yes
  tasks:
    - name: Create Alertmanager Config Secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: alertmanager-config
            namespace: monitoring
          type: Opaque
          stringData:
            alertmanager.yml: |
              global:
                smtp_smarthost: 'smtp.gmail.com:587'
                smtp_from: ''
                smtp_auth_username: ''
                smtp_auth_password: 'kkjhiesjkhgoxorx'
              route:
                receiver: 'email-notifications'
              receivers:
              - name: 'email-notifications'
                email_configs:
                - to: 'vernandosatarov@gmail.com'
                  send_resolved: true

    - name: Deploy Alertmanager
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: alertmanager
            namespace: monitoring
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: alertmanager
            template:
              metadata:
                labels:
                  app: alertmanager
              spec:
                containers:
                - name: alertmanager
                  image: prom/alertmanager:latest
                  args:
                  - '--config.file=/etc/alertmanager/alertmanager.yml'
                  - '--storage.path=/alertmanager'
                  ports:
                  - containerPort: 9093
                  volumeMounts:
                  - name: config
                    mountPath: /etc/alertmanager
                  - name: storage
                    mountPath: /alertmanager
                volumes:
                - name: config
                  secret:
                    secretName: alertmanager-config
                - name: storage
                  emptyDir: {}

    - name: Create Alertmanager Service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: alertmanager-service
            namespace: monitoring
          spec:
            selector:
              app: alertmanager
            ports:
            - port: 9093
              targetPort: 9093
            type: ClusterIP

---
# ===== playbooks/14-patch-prometheus-alerts.yml =====
- name: Add Alert Rules to Prometheus Config
  hosts: 192.168.2.50
  become: yes
  tasks:
    - name: Patch Prometheus ConfigMap with alert rules
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-config
            namespace: monitoring
          data:
            prometheus.yml: |
              global:
                scrape_interval: 15s
              scrape_configs:
                - job_name: 'prometheus'
                  static_configs:
                    - targets: ['localhost:9090']
                - job_name: 'node-exporter'
                  static_configs:
                    - targets: ['localhost:9100']
                - job_name: 'kubernetes-pods'
                  kubernetes_sd_configs:
                  - role: pod
                  relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: keep
                    regex: true
              rule_files:
                - /etc/prometheus/alert.rules.yml

    - name: Create Prometheus alert rules ConfigMap
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: prometheus-alert-rules
            namespace: monitoring
          data:
            alert.rules.yml: |
              groups:
              - name: Node Alerts
                rules:
                - alert: HighNodeCPU
                  expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
                  for: 2m
                  labels:
                    severity: warning
                  annotations:
                    summary: "High CPU usage on {{ $labels.instance }}"
                    description: "CPU usage is > 90% on {{ $labels.instance }}"
                - alert: PodCrashLooping
                  expr: kube_pod_container_status_restarts_total > 3
                  for: 2m
                  labels:
                    severity: warning
                  annotations:
                    summary: "Pod crash looping detected"
                    description: "Container has restarted more than 3 times in the last 2 minutes"

    - name: Restart Prometheus Deployment
      kubernetes.core.k8s:
        name: prometheus
        namespace: monitoring
        kind: Deployment
        api_version: apps/v1
        state: restarted